Repository DeveloperAcademy-POSTECH/2024-MC3-A03-Sgrr, pull requests merged in 2024-07, with the labels that each got.

#10 chore/#9 CoreData 'OrderForm' Entity 생성
  Sgrr/Sgrr.xcodeproj/project.pbxproj
  Sgrr/Sgrr.xcodeproj/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
  Sgrr/Sgrr/Model/Sgrr.xcdatamodeld/.xccurrentversion
  Sgrr/Sgrr/Model/Sgrr.xcdatamodeld/Sgrr.xcdatamodel/contents
  Sgrr/Sgrr/Sgrr.xcdatamodeld/Sgrr.xcdatamodel/contents
Labels: chore

#15 add/#14 코어데이터 CoredataManager 구현
  Sgrr/Sgrr.xcodeproj/project.pbxproj
  Sgrr/Sgrr.xcodeproj/xcuserdata/leewonsun.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Sgrr/Sgrr/ContentView.swift
  Sgrr/Sgrr/Manager/CoredataManager.swift
  Sgrr/Sgrr/Model/Sgrr.xcdatamodeld/Sgrr.xcdatamodel/contents
  Sgrr/Sgrr/Persistence.swift
  Sgrr/Sgrr/SgrrApp.swift
Labels: add

#19 Feat/#18
  Sgrr/Sgrr.xcodeproj/project.pbxproj
  Sgrr/Sgrr/Assets.xcassets/ImageIcon.imageset/Contents.json
  Sgrr/Sgrr/Assets.xcassets/ImageIcon.imageset/ImageIcon 1.png
  Sgrr/Sgrr/Assets.xcassets/ImageIcon.imageset/ImageIcon.png
  Sgrr/Sgrr/ImageAddView.swift
Labels: feat

#25 add/#16 Cake class 생성 및 데이터 연결 작업
  Sgrr/Sgrr.xcodeproj/project.pbxproj
  Sgrr/Sgrr/ContentView.swift
  Sgrr/Sgrr/Manager/CoredataManager.swift
  Sgrr/Sgrr/Model/Cake.swift
  Sgrr/Sgrr/Persistence.swift
  Sgrr/Sgrr/SgrrApp.swift
Labels: add
